#!/bin/bash

python="$(which python2)"
echo ""
echo "###### RUNNING Tests in python 2 ######"
echo ""
$python -m unittest tests

if [ $? -eq 0 ]; then
  python="$(which python3)"
  echo ""
  echo "###### Running Tests in python 3 ######"
  echo ""
  $python -m unittest
fi

